image: node:14.16.1-alpine

.shared_windows_runners:
  tags:
    - shared-windows
    - windows
    - windows-1809

stages:
  - prepare
  - test
  - build

before_script:
  - Set-Variable -Name "time" -Value (date -Format "%H:%m")
  - echo ${time}
  - echo "started by ${GITLAB_USER_NAME}"

prepare:
  extends:
    - .shared_windows_runners
  stage: prepare
  script:
    - npm install

test:
  extends:
    - .shared_windows_runners
  stage: test
  script:
    - npm run test

build:
  extends:
    - .shared_windows_runners
  stage: build
  script:
    - npm run electron:build-win

  # artifacts:
  #   paths:
  #     - public
  only:
    - main
