variables:
  GIT_CLEAN_FLAGS: none
  GIT_CLONE_PATH: $CI_BUILDS_DIR/kage-react

stages:
  - prepare
  - test
  - build

setup:
  stage: prepare
  script:
    - echo ${time}
    - echo "started by ${GITLAB_USER_NAME}"
    - yarn install
    - echo ${CI_RUNNER_EXECUTABLE_ARCH}
    - echo ${REACT_APP_GH_TOKEN}

test:
  tags:
    - windows-server
  stage: test
  script:
    - npm run lint:fix
    - npm run test

build-win:
  tags:
    - windows-server
  stage: build
  resource_group: windows-machines
  script:
    - npm run electron:build-win
  only:
    - release

build-mac:
  tags:
    - dora-mac-mini
  stage: build
  resource_group: mac-machines
  script:
    - npm run electron:build-mac
  only:
    - release
