variables:
  GIT_CLEAN_FLAGS: none
  GIT_CLONE_PATH: $CI_BUILDS_DIR/kage-react

stages:
  - prepare
  - test
  - build-win
  - build-mac

before_script:
  - Set-Variable -Name "time" -Value (date -Format "%H:%m")
  - echo ${time}
  - echo "started by ${GITLAB_USER_NAME}"
  - yarn install
  - echo ${CI_RUNNER_EXECUTABLE_ARCH}
test:
  tags:
    - windows-server
  stage: test
  script:
    - npm run lint:fix
    - npm run test

build-win:
  tags:
    - windows-server
  resource_group: build-machines
  script:
    - npm run electron:build-win
  only:
    - release

build-mac:
  tags:
    - dora-mac-mini
  resource_group: build-machines
  script:
    - npm run electron:build-mac
  only:
    - release
